DROP TABLE IF EXISTS public.PRODUKT;
CREATE TABLE public.PRODUKT (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    PREIS DECIMAL NOT NULL
);

INSERT INTO public.PRODUKT (ID, NAME, PREIS) VALUES (1, 'Salat', 8.5);
INSERT INTO public.PRODUKT (ID, NAME, PREIS) VALUES (2, 'Bowl', 11.0);
INSERT INTO public.PRODUKT (ID, NAME, PREIS) VALUES (3, 'Ciabatta', 1.5);
INSERT INTO public.PRODUKT (ID, NAME, PREIS) VALUES (4, 'Getränk', 2.0);
INSERT INTO public.PRODUKT (ID, NAME, PREIS) VALUES (5, 'Dip', 1.0);
INSERT INTO public.PRODUKT (ID, NAME, PREIS) VALUES (6, 'Dressing', 0.5);